# Generated by Django 3.2.13 on 2022-09-29 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll_managment', '0002_option_cant_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='user_id',
            field=models.ForeignKey(default=47, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
